import {
  siAndroid,
  siAndroidstudio,
  siAngular,
  siAnsible,
  siApachecassandra,
  siApachekafka,
  siApple,
  siArgo,
  siAstro,
  siBlender,
  siBootstrap,
  siCircleci,
  siClickhouse,
  siCloudflare,
  siCockroachlabs,
  siCoreldraw,
  siCouchbase,
  siCss,
  siDart,
  siDatadog,
  siDigitalocean,
  siDjango,
  siDocker,
  siDotnet,
  siDrizzle,
  siDuckdb,
  siElasticsearch,
  siExcalidraw,
  siExpo,
  siExpress,
  siFastapi,
  siFigma,
  siFirebase,
  siFlutter,
  siFramer,
  siGimp,
  siGithubactions,
  siGitlab,
  siGo,
  siGooglebigquery,
  siGooglecloud,
  siGradle,
  siGrafana,
  siGraphql,
  siHelm,
  siHtml5,
  siInfluxdb,
  siInkscape,
  siIonic,
  siJavascript,
  siJenkins,
  siJetpackcompose,
  siJsonwebtokens,
  siKotlin,
  siKubernetes,
  siLaravel,
  siLinux,
  siLottiefiles,
  siMariadb,
  siMiro,
  siMongodb,
  siMui,
  siMysql,
  siNeo4j,
  siNestjs,
  siNetlify,
  siNextdotjs,
  siNginx,
  siNodedotjs,
  siNotion,
  siNuxt,
  siOpensearch,
  siOpentelemetry,
  siPenpot,
  siPhp,
  siPlanetscale,
  siPostgresql,
  siPrisma,
  siPrometheus,
  siPulumi,
  siPython,
  siRabbitmq,
  siReact,
  siRedis,
  siRedux,
  siRemix,
  siRust,
  siSass,
  siSentry,
  siSketch,
  siSnowflake,
  siSpring,
  siSqlite,
  siStorybook,
  siSupabase,
  siSvelte,
  siSwagger,
  siSwift,
  siTailwindcss,
  siTanstack,
  siTerraform,
  siTrpc,
  siTypeorm,
  siTypescript,
  siVercel,
  siVite,
  siVitest,
  siVuedotjs,
  siWebflow,
  siWebpack,
  siXcode,
} from "simple-icons";

/**
 * Brand marks come from simple-icons. They are imported one by one rather
 * than looked up off the package namespace so the bundler can drop the three
 * thousand icons we do not use — a dynamic lookup would pull in the lot.
 *
 * This renders on the server, so the marks cost no client JavaScript.
 *
 * Some brands have no entry here at all: Adobe, AWS and Azure have all been
 * withdrawn from simple-icons at the trademark holders' request. Those
 * technologies still appear in the stack — TechStack falls back to the
 * monogram tile used in the header menu rather than dropping them or
 * silently substituting a different product.
 */
const ICONS = {
react: siReact,
  nextjs: siNextdotjs,
  angular: siAngular,
  vue: siVuedotjs,
  svelte: siSvelte,
  astro: siAstro,
  remix: siRemix,
  nuxt: siNuxt,
  typescript: siTypescript,
  javascript: siJavascript,
  html: siHtml5,
  css: siCss,
  sass: siSass,
  tailwind: siTailwindcss,
  bootstrap: siBootstrap,
  mui: siMui,
  redux: siRedux,
  tanstack: siTanstack,
  vite: siVite,
  webpack: siWebpack,
  storybook: siStorybook,
  vitest: siVitest,
  graphql: siGraphql,
  figma: siFigma,
  nodejs: siNodedotjs,
  nestjs: siNestjs,
  express: siExpress,
  python: siPython,
  django: siDjango,
  fastapi: siFastapi,
  go: siGo,
  rust: siRust,
  spring: siSpring,
  php: siPhp,
  laravel: siLaravel,
  dotnet: siDotnet,
  trpc: siTrpc,
  prisma: siPrisma,
  rabbitmq: siRabbitmq,
  kafka: siApachekafka,
  docker: siDocker,
  kubernetes: siKubernetes,
  swagger: siSwagger,
  jwt: siJsonwebtokens,
  postgresql: siPostgresql,
  mysql: siMysql,
  mariadb: siMariadb,
  mongodb: siMongodb,
  redis: siRedis,
  sqlite: siSqlite,
  supabase: siSupabase,
  firebase: siFirebase,
  elasticsearch: siElasticsearch,
  neo4j: siNeo4j,
  cassandra: siApachecassandra,
  clickhouse: siClickhouse,
  snowflake: siSnowflake,
  bigquery: siGooglebigquery,
  influxdb: siInfluxdb,
  cockroach: siCockroachlabs,
  duckdb: siDuckdb,
  planetscale: siPlanetscale,
  drizzle: siDrizzle,
  typeorm: siTypeorm,
  couchbase: siCouchbase,
  opensearch: siOpensearch,
  sketch: siSketch,
  framer: siFramer,
  miro: siMiro,
  notion: siNotion,
  webflow: siWebflow,
  lottie: siLottiefiles,
  blender: siBlender,
  penpot: siPenpot,
  excalidraw: siExcalidraw,
  inkscape: siInkscape,
  gimp: siGimp,
  coreldraw: siCoreldraw,
  flutter: siFlutter,
  dart: siDart,
  kotlin: siKotlin,
  swift: siSwift,
  android: siAndroid,
  apple: siApple,
  expo: siExpo,
  ionic: siIonic,
  xcode: siXcode,
  androidstudio: siAndroidstudio,
  gradle: siGradle,
  compose: siJetpackcompose,
  gcp: siGooglecloud,
  terraform: siTerraform,
  githubactions: siGithubactions,
  gitlab: siGitlab,
  vercel: siVercel,
  cloudflare: siCloudflare,
  nginx: siNginx,
  linux: siLinux,
  prometheus: siPrometheus,
  grafana: siGrafana,
  ansible: siAnsible,
  helm: siHelm,
  argo: siArgo,
  datadog: siDatadog,
  sentry: siSentry,
  digitalocean: siDigitalocean,
  netlify: siNetlify,
  pulumi: siPulumi,
  jenkins: siJenkins,
  circleci: siCircleci,
  otel: siOpentelemetry,
} as const;

export type TechLogoSlug = keyof typeof ICONS;

export function techLogoTitle(slug: TechLogoSlug) {
  return ICONS[slug].title;
}

/**
 * Several brands are black or near-black — Next.js, Remix and Angular all
 * are — which would make them invisible on this background. Anything below
 * the luminance floor falls back to off-white instead of its brand colour.
 */
function displayColor(hex: string) {
  const channel = (at: number) => parseInt(hex.slice(at, at + 2), 16) / 255;
  const luminance = 0.2126 * channel(0) + 0.7152 * channel(2) + 0.0722 * channel(4);
  return luminance < 0.22 ? "#E6E4F0" : `#${hex}`;
}

export function TechLogo({ slug, className }: { slug: TechLogoSlug; className?: string }) {
  const icon = ICONS[slug];

  return (
    <svg
      role="img"
      aria-label={icon.title}
      viewBox="0 0 24 24"
      className={className ?? "h-7 w-7"}
      fill={displayColor(icon.hex)}
    >
      <path d={icon.path} />
    </svg>
  );
}
